#! /bin/sh

# 导出当前用户的crontab内容
$(crontab -l > /tmp/crontab.file)

# 删除crontab文件内容
$(sed -i /net-test-logrotate.sh/d /tmp/crontab.file)
$(sed -i /net-test.pl/d /tmp/crontab.file)

$(grep -i \"net-test-logrotate.sh\" /tmp/crontab.file)
if test $? 
then
    sed -i /net-test-logrotate.sh/d /tmp/crontab.file
fi
$(grep -i \"net-test.pl\" /tmp/crontab.file)
if test $?
then
    sed -i /net-test.pl/d /tmp/crontab.file
fi

# 将文件倒回入crontab内
$(crontab /tmp/crontab.file)
if test $?
then
    rm -f /tmp/crontab.file
    echo "uninstall done ~~~~~"
fi